version: '3'
services:
  api:
    image: mc-api:latest
    ports:
      - "8000:8000"
    depends_on:
      - db
  db:
    image: postgres:latest
    environment:
      - POSTGRES_USER=mc
      - POSTGRES_PASSWORD=mc
      - POSTGRES_DB=minicube
    ports:
      - "5432:5432"
